create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "slug" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."categories" enable row level security;

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX categories_slug_key ON public.categories USING btree (slug);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."categories" add constraint "categories_slug_key" UNIQUE using index "categories_slug_key";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

-- Read-only from the app. The record form only picks from this list, so adding
-- or removing a category is a deliberate change made against the database —
-- which is what keeps the sidebar short and stops a typo becoming a category.
create policy "Allow select for everyone"
on "public"."categories"
as permissive
for select
to public
using (true);


-- Seeded in the order they should appear: the sidebar reads created_at.
insert into "public"."categories" ("name", "slug") values
    ('백엔드', 'backend'),
    ('프론트엔드', 'frontend'),
    ('인프라', 'infra'),
    ('CS', 'cs');

alter table "public"."records" add column "category_id" bigint;

alter table "public"."records"
    add constraint "records_category_id_fkey"
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL not valid;

alter table "public"."records" validate constraint "records_category_id_fkey";

-- Backfill by exact title. Rows that do not match are left null and simply do
-- not appear under a category, so a miss is visible rather than silent.
update "public"."records" set "category_id" = (select "id" from "public"."categories" where "slug" = 'backend')
where "title" in (
    '실시간 데이터를 수집하는 Node.js Worker의 안정성과 구조 개선하기',
    '모두에게 공평한 모임 장소 추천하기 (2) – 후보 탐색 알고리즘 만들기',
    '웹으로 만든 4컷 포토부스 (3) – AI를 활용하여 사진을 캐릭터로 바꾸기',
    '웹으로 만든 4컷 포토부스 (2) – 프린트 큐와 워커로 인쇄 분리하기',
    'Node.js로 만든 Worker Application으로 시계열 데이터 저장 & 실시간 스트리밍하기',
    '동시 요청으로 인한 중복 실행을 분산 락 없이 막기'
);

update "public"."records" set "category_id" = (select "id" from "public"."categories" where "slug" = 'frontend')
where "title" in (
    '웹으로 만든 4컷 포토부스 (1) – 촬영부터 사진 합성, 공유까지',
    'Next.js에서 동적으로 생성되는 OpenGraph 이미지 구현해보기',
    'React Hook과 SWR로 편리하게 유저 인증 상태 관리하기'
);

update "public"."records" set "category_id" = (select "id" from "public"."categories" where "slug" = 'infra')
where "title" in (
    '모두에게 공평한 모임 장소 추천하기 (1) – MOTIS로 대중교통 길찾기 서버 구축하기',
    '3년을 굴린 폴리레포를 모노레포로 다시 쓰기'
);
